### ISSUE TITLE
Nearest Playgrounds

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/more-than-just-datum#1]
@muxlowc @mackenzierose

I'm not too sure on how to extend the white blocks on the data under "Nearest Playgrounds". I tried multiple ways, but I just seem to keep having a hard time :(

**Comment by muxlowc** [comment]
@Sophia-Villamayor I think you may have put one too many divs in here, remove that third one, and move your classes (ie. unit unit-s...) into the div above it, like this:

```
<div class="grid">
    <div class="color unit xs-1 s-1 m-1-4 l-1-4 xl-1-4 gutter-1-2 pad-t-1-2">

        <h2 class="bold giga list-group push-1-2">Nearest playgrounds</h2>
```

2) Also, your "nearest playgrounds" should be an h2 - your h1 will actually surround your <img > tag where your logo is :)

3) fyi, markbot will likely ask you for a UL / LI.. so instead of using divs for this section, you should use UL / LIs like this:

```
<ul class="near-list list-group push-0">
        <li class="card island-1-2 push-1-2">
          <h3 class="mega push-0">373</h3>
          <dl class="list-group-inline push-0">
            <dt class="push-0 italic milli">Distance</dt>
            <dd class="push-0">0.75 km</dd>
          </dl>
        </li>
```

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
